language: node_js
node_js:
  - "stable"

before_script:
  - npm install
  - npm run build

script:
  - npm run test:coverage

after_script:
  - npm install coveralls
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

branches:
  only:
    - master
